### ISSUE TITLE
Incompatibility with find-files-in-project v6.0.0 (breaks test suite)

### ISSUE THREAD

**Issue by Apteryks** [jorgenschaefer/elpy#1889]
# Summary

It seems the latest version of the find-files-in-project departs from its previous API a bit, which breaks the build of Elpy.

# Steps to reproduce

$ guix build emacs-elpy on an up-to-date GNU Guix version (e.g., commit: 359e9053521bfab34b5861925398fc5f329d4ca3)

The test suite fails with the following output:

```
    (wrong-number-of-arguments
     #[(keyword &optional find-directory-p)
       "\306 \307       
\"310\311\312
             \313#\314Q\315\316
                               !\317\320#\321\203(       [default-directory keyword find-directory-p cmd ffip-patterns fd-file-pattern ffip-get-project-root-directory ffip-create-shell-command "^" mapconcat ...]
       6
       ("/gnu/store/6vzv74j14nph2hk89f5b0r3r6ngaa2ii-emacs-find-file-in-project-6.0.0/share/emacs/site-lisp/find-file-in-project.elc" . 13956)]
     3)

FTest elpy-find--test-file-should-return-nil-if-not-found backtrace:


Test elpy-find--test-file-should-return-nil-if-not-found condition:

    (wrong-number-of-arguments
     #[(keyword &optional find-directory-p)
       "\306 \307       
\"310\311\312
             \313#\314Q\315\316
                               !\317\320#\321\203(       [default-directory keyword find-directory-p cmd ffip-patterns fd-file-pattern ffip-get-project-root-directory ffip-create-shell-command "^" mapconcat ...]
       6
       ("/gnu/store/6vzv74j14nph2hk89f5b0r3r6ngaa2ii-emacs-find-file-in-project-6.0.0/share/emacs/site-lisp/find-file-in-project.elc" . 13956)]
     3)

F..Test elpy-find-file-should-open-test-file backtrace:


Test elpy-find-file-should-open-test-file condition:

    (wrong-number-of-arguments
     #[(keyword &optional find-directory-p)
       "\306 \307       
\"310\311\312
             \313#\314Q\315\316
                               !\317\320#\321\203(       [default-directory keyword find-directory-p cmd ffip-patterns fd-file-pattern ffip-get-project-root-directory ffip-create-shell-command "^" mapconcat ...]
       6
       ("/gnu/store/6vzv74j14nph2hk89f5b0r3r6ngaa2ii-emacs-find-file-in-project-6.0.0/share/emacs/site-lisp/find-file-in-project.elc" . 13956)]
     3)

F.................................................................................................................................................................................................................................................................................................................................................................

Ran 435 tests in 31.284 seconds
9 unexpected results:
   FAILED  elpy-find--test-file-should-find-implementation-file-same-directory
   FAILED  elpy-find--test-file-should-find-implementation-file-superdirectory
   FAILED  elpy-find--test-file-should-find-test-file-in-test-directory
   FAILED  elpy-find--test-file-should-find-test-file-in-test-superdirectory
   FAILED  elpy-find--test-file-should-find-test-file-in-tests-directory
   FAILED  elpy-find--test-file-should-find-test-file-in-tests-superdirectory
   FAILED  elpy-find--test-file-should-find-test-file-same-directory
   FAILED  elpy-find--test-file-should-return-nil-if-not-found
   FAILED  elpy-find-file-should-open-test-file
command "ert-runner" failed with status 1
builder for `/gnu/store/an8sm50g6jlw4jlphb11aa8rhimcm6yp-emacs-elpy-1.35.0.drv' failed with exit code 1
@ build-failed /gnu/store/an8sm50g6jlw4jlphb11aa8rhimcm6yp-emacs-elpy-1.35.0.drv - 1 builder for `/gnu/store/an8sm50g6jlw4jlphb11aa8rhimcm6yp-emacs-elpy-1.35.0.drv' failed with exit code 1
```

# My configuration
## OS 
Guix System

**Comment by sten0** [comment]
Fixed by PR #1882

**Comment by Apteryks** [comment]
Eh, thanks for the quick reply.  I like how the fix is simple.  Will apply it as an in-package patch for now in Guix.  Thank you!

**Comment by Apteryks** [comment]
@sten0 It seems the fix is incomplete, I'm still getting this:
```
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
........................................................................Test elpy-find--test-file-should-find-implementation-file-superdirectory backtrace:


Test elpy-find--test-file-should-find-implementation-file-superdirectory condition:

    (wrong-type-argument stringp nil)

F.Test elpy-find--test-file-should-find-test-file-in-test-superdirectory backtrace:


Test elpy-find--test-file-should-find-test-file-in-test-superdirectory condition:

    (wrong-type-argument stringp nil)

F.Test elpy-find--test-file-should-find-test-file-in-tests-superdirectory backtrace:


Test elpy-find--test-file-should-find-test-file-in-tests-superdirectory condition:

    (wrong-type-argument stringp nil)

F......................................................................................................................................................................................................................................................................................................................................................................

Ran 435 tests in 81.759 seconds
3 unexpected results:
   FAILED  elpy-find--test-file-should-find-implementation-file-superdirectory
   FAILED  elpy-find--test-file-should-find-test-file-in-test-superdirectory
   FAILED  elpy-find--test-file-should-find-test-file-in-tests-superdirectory
command "ert-runner" failed with status 1
```

**Comment by Apteryks** [comment]
Backtrace of one of the failing test:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  f-exists\?(nil)
  f-equal\?(nil "/tmp/elpy-test-SwRzoH/test/test_foo.py")
  apply(f-equal\? (nil "/tmp/elpy-test-SwRzoH/test/test_foo.py"))
  (setq value-102 (apply fn-100 args-101))
  (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc (list '(should (f-equal\? (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (list :form (cons fn-100 args-101)) (if (eql value-102 'ert-form-evaluation-aborted-103) nil (list :value value-102)) (let ((-explainer- (and (symbolp ...) (get ... ...)))) (if -explainer- (progn (list :explanation (apply -explainer- args-101))))))) (ert--signal-should-execution form-description-104))
  (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc (list '(should (f-equal\? ... ...))) (list :form (cons fn-100 args-101)) (if (eql value-102 'ert-form-evaluation-aborted-103) nil (list :value value-102)) (let ((-explainer- (and ... ...))) (if -explainer- (progn (list :explanation ...)))))) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104))
  (let (form-description-104) (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc (list '(should ...)) (list :form (cons fn-100 args-101)) (if (eql value-102 'ert-form-evaluation-aborted-103) nil (list :value value-102)) (let ((-explainer- ...)) (if -explainer- (progn ...))))) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104)))
  (let ((value-102 'ert-form-evaluation-aborted-103)) (let (form-description-104) (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc (list '...) (list :form (cons fn-100 args-101)) (if (eql value-102 ...) nil (list :value value-102)) (let (...) (if -explainer- ...)))) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104))) value-102)
  (let ((fn-100 #'f-equal\?) (args-101 (list (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (let ((value-102 'ert-form-evaluation-aborted-103)) (let (form-description-104) (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc (list ...) (list :form ...) (if ... nil ...) (let ... ...))) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104))) value-102))
  (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'(lambda nil nil)) (if (require 'projectile nil t) (progn (fmakunbound 'find-file-in-project) (let ((fn-95 #'f-equal\?) (args-96 (list (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (let ((value-97 'ert-form-evaluation-aborted-98)) (let (form-description-99) (if (unwind-protect ... ... ...) nil (ert-fail form-description-99))) value-97)))) (defalias 'find-file-in-project #'(lambda nil nil)) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let ((fn-100 #'f-equal\?) (args-101 (list (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (let ((value-102 'ert-form-evaluation-aborted-103)) (let (form-description-104) (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq form-description-104 (nconc ... ... ... ...)) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104))) value-102)))
  (progn (elpy-testcase-create-files project-root '("pkg/foo.py" "test/test_foo.py")) (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'(lambda nil nil)) (if (require 'projectile nil t) (progn (fmakunbound 'find-file-in-project) (let ((fn-95 #'f-equal\?) (args-96 (list ... ...))) (let ((value-97 ...)) (let (form-description-99) (if ... nil ...)) value-97)))) (defalias 'find-file-in-project #'(lambda nil nil)) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let ((fn-100 #'f-equal\?) (args-101 (list (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (let ((value-102 'ert-form-evaluation-aborted-103)) (let (form-description-104) (if (unwind-protect (setq value-102 ...) (setq form-description-104 ...) (ert--signal-should-execution form-description-104)) nil (ert-fail form-description-104))) value-102))))
  (unwind-protect (progn (elpy-testcase-create-files project-root '("pkg/foo.py" "test/test_foo.py")) (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'(lambda nil nil)) (if (require 'projectile nil t) (progn (fmakunbound 'find-file-in-project) (let ((fn-95 ...) (args-96 ...)) (let (...) (let ... ...) value-97)))) (defalias 'find-file-in-project #'(lambda nil nil)) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let ((fn-100 #'f-equal\?) (args-101 (list (elpy-find--test-file) (f-join project-root "test/test_foo.py")))) (let ((value-102 'ert-form-evaluation-aborted-103)) (let (form-description-104) (if (unwind-protect ... ... ...) nil (ert-fail form-description-104))) value-102)))) (condition-case nil (progn (delete-directory project-root t)) (error nil)))
  (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protect (progn (elpy-testcase-create-files project-root '("pkg/foo.py" "test/test_foo.py")) (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'(lambda nil nil)) (if (require 'projectile nil t) (progn (fmakunbound 'find-file-in-project) (let (... ...) (let ... ... value-97)))) (defalias 'find-file-in-project #'(lambda nil nil)) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let ((fn-100 #'f-equal\?) (args-101 (list ... ...))) (let ((value-102 ...)) (let (form-description-104) (if ... nil ...)) value-102)))) (condition-case nil (progn (delete-directory project-root t)) (error nil))))
  (progn (setq elpy-rpc-timeout 100) (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protect (progn (elpy-testcase-create-files project-root '("pkg/foo.py" "test/test_foo.py")) (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'(lambda nil nil)) (if (require 'projectile nil t) (progn (fmakunbound ...) (let ... ...))) (defalias 'find-file-in-project #'(lambda nil nil)) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let ((fn-100 ...) (args-101 ...)) (let (...) (let ... ...) value-102)))) (condition-case nil (progn (delete-directory project-root t)) (error nil)))))
  (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protect (progn (elpy-testcase-create-files project-root '("pkg/foo.py" "test/test_foo.py")) (progn (find-file (f-join project-root "pkg/foo.py")) (elpy-set-project-root project-root) (defalias 'projectile-find-file #'...) (if (require ... nil t) (progn ... ...)) (defalias 'find-file-in-project #'...) (require 'find-file-in-project) (fmakunbound 'projectile-find-file) (let (... ...) (let ... ... value-102)))) (condition-case nil (progn (delete-directory project-root t)) (error nil))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protect (progn (elpy-testcase-create-files project-root '...) (progn (find-file ...) (elpy-set-project-root project-root) (defalias ... ...) (if ... ...) (defalias ... ...) (require ...) (fmakunbound ...) (let ... ...))) (condition-case nil (progn (delete-directory project-root t)) (error nil))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protect (progn (elpy-testcase-create-files project-root ...) (progn ... ... ... ... ... ... ... ...)) (condition-case nil (progn ...) (error nil))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (progn (if elpy-enabled-p (progn (message "Elpy was not deactivated by the previous test, dea...") (elpy-disable))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ((project-root ...)) (unwind-protect (progn ... ...) (condition-case nil ... ...)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if (and (boundp 'elpy-enabled-p) elpy-enabled-p) (progn (elpy-disable))))
  (unwind-protect (progn (if elpy-enabled-p (progn (message "Elpy was not deactivated by the previous test, dea...") (elpy-disable))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq elpy-rpc-timeout 100) (let (...) (unwind-protect ... ...))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if (and (boundp 'elpy-enabled-p) elpy-enabled-p) (progn (elpy-disable)))) (let ((--dolist-tail-- (process-list)) proc) (while --dolist-tail-- (setq proc (car --dolist-tail--)) (if (member proc old-process-list) nil (kill-process proc)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((kill-buffer-query-functions nil)) (let ((--dolist-tail-- (buffer-list)) buf) (while --dolist-tail-- (setq buf (car --dolist-tail--)) (if (member buf old-buffer-list) nil (kill-buffer buf)) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (let ((old-process-list (process-list)) (old-buffer-list (buffer-list))) (unwind-protect (progn (if elpy-enabled-p (progn (message "Elpy was not deactivated by the previous test, dea...") (elpy-disable))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ... ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if (and (boundp 'elpy-enabled-p) elpy-enabled-p) (progn (elpy-disable)))) (let ((--dolist-tail-- (process-list)) proc) (while --dolist-tail-- (setq proc (car --dolist-tail--)) (if (member proc old-process-list) nil (kill-process proc)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((kill-buffer-query-functions nil)) (let ((--dolist-tail-- (buffer-list)) buf) (while --dolist-tail-- (setq buf (car --dolist-tail--)) (if (member buf old-buffer-list) nil (kill-buffer buf)) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  eval((let ((old-process-list (process-list)) (old-buffer-list (buffer-list))) (unwind-protect (progn (if elpy-enabled-p (progn (message "Elpy was not deactivated by the previous test, dea...") (elpy-disable))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ...) (and ... ...)))) (if (and (boundp 'elpy-enabled-p) elpy-enabled-p) (progn (elpy-disable)))) (let ((--dolist-tail-- (process-list)) proc) (while --dolist-tail-- (setq proc (car --dolist-tail--)) (if (member proc old-process-list) nil (kill-process proc)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((kill-buffer-query-functions nil)) (let ((--dolist-tail-- (buffer-list)) buf) (while --dolist-tail-- (setq buf (car --dolist-tail--)) (if (member buf old-buffer-list) nil (kill-buffer buf)) (setq --dolist-tail-- (cdr --dolist-tail--))))))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by Apteryks** [comment]
Taking `elpy-find--test-file-should-find-test-file-in-test-superdirectory` as a case study, the elpy-testcase harness leaves us with `default-directory` set to a `pkg` subdirectory rather than the top directory: `/tmp/elpy-test-9iG9gm/pkg`.

This causes the new behavior of ffip-search-project to use `default-directory` as the project root, which in turn causes `elpy-find--test-file` to not find the 'test_' prefixed file.  The test directory hierarchy looks like:

```
/tmp/elpy-test-9iG9gm
├── pkg
│   └── foo.py
└── test
    └── test_foo.py
```

**Comment by Apteryks** [comment]
The fix is this:
```
@@ -1627,7 +1627,8 @@ A test file is named test_<name>.py if the current file is
             (let ((projectile-project-root project-root))
               (projectile-current-project-files)))
            ((fboundp 'find-file-in-project)
-            (cl-map 'list 'cdr (ffip-project-search nil nil project-root)))
+	    (let ((ffip-project-root project-root))
+              (cl-map 'list 'cdr (ffip-project-search nil nil))))
            (t '())))
          (file (if impl-file
                     (cl-remove-if (lambda (file)
```
