### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by AttilaVM** [jorgenschaefer/elpy#761]
Hello everyone!

I got : “inconsistent use of tabs and spaces in indentation” with elpy.
I worked around it with using space instead of tabs:
```
(setq-default indent-tabs-mode nil)
```
I hope it will help others.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the information!

Emacs' `python-mode`, which Elpy uses, should already by default set `indent-tabs-mode` to `nil` – did you change this in your personal configuration?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is resolved. Please do not hesitate to open a new issue if you have further problems, and enjoy Elpy!

**Comment by s-cosseddu** [comment]
Just a note, I can confirm this misbehaviour still exists for Emacs 24.5.1 on Mac OSX and elpy 1.12.0 installed from melpa. As mentioned, it is solved setting `indent-tabs-mode` to nil. 

Thanks for your work ;)

**Comment by jorgenschaefer** [comment]
Please test this with `emacs -Q` to make sure this is not some kind of local misconfiguration.

**Comment by MichaelLiuzzi** [comment]
Can confirm this is a problem for me as well -- emacs 24.5.1, elpy 1.12

**Comment by Krisselack** [comment]
Thank you, worked for me as well - win7, python 3.5.2; emacs 25.2.1; elpy 1.8.0. 
The issue started with the 2nd level of indentation, where apparently only one space worked (instead of 4).

**Comment by yitang** [comment]
Hi @jorgenschaefer I'm having problems copying a snippet of code from python to org-mode's src block without seeing the inconsistent tab/space problem. 

I reset indent-tabs-mode to nil.

**Comment by jorgenschaefer** [comment]
I have no idea why that might be. Does it happen without Elpy as well? If so, it's something in your Emacs configuration.

**Comment by yitang** [comment]
yeah, it sounds like my emacs config has some issues..

**Comment by averter** [comment]
I am also experiencing the same issue when eval a python source block, which has two or more for loops, using org-babel. When editing the code in a single file everything works as expected. It is an extremely annoying issue.

**Comment by galaunay** [comment]
Elpy is only used to evaluate org python source block when you use poly-org-mode.
Is it the case ?

**Comment by aang7** [comment]
> 

same

**Comment by aang7** [comment]
> I am also experiencing the same issue when eval a python source block, which has two or more for loops, using org-babel. When editing the code in a single file everything works as expected. It is an extremely annoying issue.

same here

**Comment by averter** [comment]
> Elpy is only used to evaluate org python source block when you use poly-org-mode. Is it the case ?

No, I never installed such package.
